# Generated by Django 5.1.4 on 2024-12-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_remove_product_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='selling_price',
        ),
    ]
