# Generated by Django 5.1.4 on 2024-12-18 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_remove_product_selling_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='trending',
        ),
    ]
