# Generated by Django 5.1.4 on 2024-12-19 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_rename_catagory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='original_price',
            new_name='price',
        ),
    ]
