# Generated by Django 5.1.4 on 2024-12-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_rename_original_price_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=False, help_text='0-show,1-Hidden'),
        ),
    ]
