# Generated by Django 5.1.4 on 2024-12-24 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0011_customerdetail_alter_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='customer_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shop.customerdetail'),
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
