# Generated by Django 5.1.4 on 2024-12-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0015_payment_orderplaced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetail',
            name='user',
        ),
    ]
